services:

  bot-node:
    build:
      context: .
    container_name: support-bot-node
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
    networks:
      - network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:alpine
    container_name: support-redis-node
    restart: always
    volumes:
      - ./redis/data/:/data
    networks:
      - network

networks:
  network:
